esphome:
  name: esphome-web-f558ac
  friendly_name: Kaffeemaschine

esp8266:
  board: d1_mini


# Enable Home Assistant API
api:
  encryption:
    key: "SyHgHI5goGbmkLgDVFjiC41jOrnL9Fu9DdYiAfHAd64="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-F558Ac"
    password: "l4zMjN3Ud8RZ"

captive_portal:


# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0

external_components:
  - source: github://nocheinname/Philips-Smart-Coffee@main

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    id: uart_mainboard

  # UART connected to the display
  - tx_pin: GPIO15
    rx_pin: GPIO13
    baud_rate: 115200
    id: uart_display

philips_series_2200:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO12
  id: philip

text_sensor:
  - platform: philips_status_sensor
    controller_id: philip
    id: status
    name: "Status"

switch:
  - platform: philips_power_switch
    controller_id: philip
    name: "Power"
    icon: mdi:coffee-maker

button:
  - platform: philips_action_button
    controller_id: philip
    action: MAKE_COFFEE
    name: "Make Coffee"
    icon: mdi:coffee

  - platform: philips_action_button
    controller_id: philip
    action: SELECT_HOT_WATER
    name: "Select Hot Water"
    icon: mdi:tea

  - platform: philips_action_button
    controller_id: philip
    action: PLAY_PAUSE
    name: "Select play/pause"
    icon: mdi:play-pause

number:
  - platform: philips_bean_settings
    name: "Coffee beans"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE

  - platform: philips_size_settings
    name: "Coffee size"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE
